services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - task-list-api
    environment:
      - MYSQL_DATABASE=task_list
      - MYSQL_ROOT_PASSWORD=password
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app/code
    ports:
      - 8000:8080
    networks:
      - task-list-api
    volumes:
      - ./:/app/code
    environment:
      - ENV=local
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=task_list
      - JWT_SECRET_KEY=jwt_secret
    command: /bin/sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload"

networks:
  task-list-api:
volumes:
  mysql:
  mysql_config:
