services:
  mysql-test:
    image: mysql:8.0
    container_name: mysql-test
    restart: always
    ports:
      - 3306:3306
    networks:
      - task-list-api-test
    environment:
      - MYSQL_DATABASE=task_list_test
      - MYSQL_ROOT_PASSWORD=password
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - mysql_test:/var/lib/mysql
      - mysql_test_config:/etc/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 5
  app-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-test
    depends_on:
      mysql-test:
        condition: service_healthy
    working_dir: /app/code
    ports:
      - 8000:8080
    networks:
      - task-list-api-test
    volumes:
      - ./:/app/code
    environment:
      - ENV=local
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=task_list_test
    command: /bin/sh -c "alembic upgrade head && pytest"

networks:
  task-list-api-test:
volumes:
  mysql_test:
  mysql_test_config:
